name: ubuntu_frame_launcher
description: A launcher for Ubuntu Frame in Flutter
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ini: ^2.1.0
  path: ^1.8.3
  xdg_directories: ^1.0.4
  xdg_icons: ^0.0.5
  wayland:
    git:
      url: https://github.com/robert-ancell/wayland.dart
  get_it: ^7.6.4
  logging: ^1.2.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  mockito: ^5.4.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
