name: salto-ubuntu-frame
adopt-info: ubuntu-frame
summary: The foundation for many embedded graphical display implementations
description: ubuntu-frame is a simple fullscreen shell (based on Wayland) used for kiosks, industrial displays, digital signage, smart mirrors, etc.
confinement: strict
base: core22
license: GPL-3.0
compression: lzo
package-repositories:
  - type: apt
    ppa: mir-team/release

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: riscv64

environment:
  # Prep for Mir
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/mir/server-platform
  LIBINPUT_QUIRKS_DIR: ${SNAP}/usr/share/libinput
  # Setup XKB
  XKB_CONFIG_ROOT: $SNAP/usr/share/X11/xkb
  # Setup diagnostic
  MIR_SERVER_DIAGNOSTIC_PATH: $SNAP_COMMON/diagnostic/diagnostic.txt

layout:
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/drirc.d:  # Used by mesa-core22 for app specific workarounds
    symlink: $SNAP_COMMON/graphics/drirc.d

apps:
  ubuntu-frame:
    command-chain:
    - bin/run-user
    - bin/run-frame
    - bin/graphics-core22-wrapper
    command: usr/local/bin/frame
    plugs:
      - opengl                # for compositing
      - login-session-control # to run as a user login (e.g. from a VT)
      - x11                   # to run on a host X11 server
      - network-bind          # to run via X-forwarding (e.g. development in a container/VM)
      - hardware-observe      # libinput likes to scan udev
    slots:
      - wayland

  daemon:
    command-chain:
    - bin/run-daemon
    - bin/run-frame
    - bin/graphics-core22-wrapper
    command: usr/local/bin/frame
    daemon: simple
    restart-delay: 3s
    environment:
      # XDG config
      XDG_CONFIG_HOME: $SNAP_DATA
      HOME: $SNAP_DATA
    plugs:
      - hardware-observe      # libinput likes to scan udev
      - opengl
    slots:
      - wayland
  
  conf-wait:
    command: bin/listen-display-config
    daemon: simple
    restart-delay: 5s
    slots:
      - ubuntu-frame-config

  screenshot:
    command-chain:
    - bin/anon-shm-preload
    - bin/run-client
    - bin/graphics-core22-wrapper
    command: bin/screenshot
    plugs:
      - opengl
    slots:
      # Should be a plug but one snap can't have both the wayland slot and plug. This works.
      - wayland

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

slots:
  ubuntu-frame-diagnostic:
    interface: content
    content: diagnostic-text
    write: 
      - $SNAP_COMMON/diagnostic
  ubuntu-frame-config:
    interface: content
    content: config-files
    write:
      - $SNAP_DATA/ext-config

parts:
  ubuntu-frame:
    override-pull: |
      craftctl default
      mir_version=`LANG=C apt-cache policy mir-graphics-drivers-desktop | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      # work around https://github.com/diddlesnaps/snapcraft-multiarch-action/issues/22
      git config --global --add safe.directory ${CRAFT_PROJECT_DIR}
      recipe_version=`git -C ${CRAFT_PROJECT_DIR} rev-list --count HEAD`
      craftctl set version=$recipe_version-mir$mir_version
      if echo $mir_version | grep -e '+dev' -e '~rc' -q; then craftctl set grade=devel; else craftctl set grade=stable; fi
    plugin: cmake
    source: src
    build-packages:
      - pkg-config
      - libmiral-dev
      - libwayland-dev
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libapparmor-dev
      - libfreetype6-dev
    stage-packages:
      - libboost-filesystem1.74.0
      - libboost-iostreams1.74.0
      # Stage libmiral<n> indirectly as we cannot (since core22) do `try:/else:`
      - libmiral-dev
    prime:
      # Do not prime the `-dev` part of libmiral-dev, we don't need it (just the libmiral<n> dependency)
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/lib/*/libmir*.so

  assets:
    plugin: nil
    stage-packages:
    - fonts-ubuntu
    prime:
    - usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf

  platform:
    plugin: nil
    stage-packages:
      - mir-platform-graphics-gbm-kms
      - mir-platform-graphics-x
      - mir-platform-graphics-eglstream-kms
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
      - usr/share/libinput

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  scripts:
    plugin: dump
    source: scripts
    stage-packages:
      - inotify-tools

  anon-shm-preload:
    source: https://github.com/MirServer/anon-shm-preload.git
    plugin: cmake

  grim:
    plugin: nil
    stage-packages: [grim]
    prime:
      - -usr/share/fonts/truetype/dejavu

  graphics-core22:
    after:
      - ubuntu-frame
      - assets
      - platform
      - icons
      - scripts
      - grim
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22
      rm -rf ${CRAFT_PRIME}/usr/{doc,man,lintian,pkgconfig,X11}

    prime:
      - bin/graphics-core22-wrapper
