name: Close Snaps

on:
  pull_request:
    types: [closed]

permissions: {}

jobs:
  close:
    runs-on: ubuntu-latest
    permissions: {}

    timeout-minutes: 5

    steps:
    - name: Close obsolete channels
      uses: canonical/actions/close-snap@78e8dd5f693653767f2c60c4a6a421a1ebed35af # release @ 2025.06.05
      continue-on-error: true
      with:
        channel: 24/edge/pr${{ github.event.number }}
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
