name: Snap

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Snap:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        platform:
        - amd64
        - armhf
        - arm64

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # needed for version determination

    - name: Patch PPA and version
      run: |
        sed -i 's@mir-team/release@mir-team/dev@' snap/snapcraft.yaml
        sed -i 's@rev-list --count@rev-parse --short@' snap/snapcraft.yaml

    - name: Build and publish the snap
      uses: canonical/actions/build-snap@multiarch
      with:
        architecture: ${{ matrix.platform }}
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
        publish: ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}
        publish-channel: 22/edge/pr${{ github.event.number }}
