name: Snap

on:
  push:
    branches:
    - staging
    - trying
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Snap:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # needed for version determination

    - name: Patch Mir channel
      run: |
        sed -i 's@- mir-core20@\0/latest/edge@' snap/snapcraft.yaml

    - name: Build and publish the snap
      uses: canonical/actions/build-snap@release
      with:
        snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
        publish: ${{ github.event_name == 'pull_request' && github.repository == github.event.pull_request.head.repo.full_name }}
        publish-channel: edge/pr${{ github.event.number }}
