name: TICS

on:
#  push:
#    branches:
#    - main
  schedule:
  # 5:04 on a Wednesday
  - cron: 5 4 * * 3
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo add-apt-repository --yes ppa:mir-team/dev
        sudo apt install --yes \
          build-essential \
          libapparmor-dev \
          libboost-iostreams-dev \
          libgtest-dev \
          libgmock-dev \
          libfreetype6-dev \
          libmiral-dev \
          libmirserver-dev \
          libwayland-dev \
          ninja-build \
          pkg-config

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        cache: true

    - name: Build
      run: |
        cmake -Bbuild src
        cmake --build build

    - name: Run TICS analysis
      uses: tiobe/tics-github-action@v3
      with:
        mode: qserver
        project: ubuntu-frame
        viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
        ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
        installTics: true
