#!/bin/bash
set -euo pipefail

graphics=$SNAP_COMMON/graphics
new_shared_graphics=$SNAP_COMMON/new_shared_graphics

if [ -e "${new_shared_graphics}" ]
then
  rm -rf "${new_shared_graphics}"
fi
mkdir -p "${new_shared_graphics}"

copy_branches() {
  root="$1"

  while [ $# -gt 1 ]; do
    for base in $(find "$SNAP/graphics" -maxdepth 1 -name "${root}*")
    do
      source="${base}/$2"
      if [ -e "${source}" ]
      then
        dest_dir="$(dirname "${new_shared_graphics}/${root}/$2")"
        mkdir -p "${dest_dir}"
        cp -r "${source}" "${dest_dir}"
      fi
    done
    shift
  done
}

copy_branches etc "vdpau_wrapper.cfg"
copy_branches usr "lib/$(arch)-linux-gnu/vdpau/" "share/drirc.d" "share/libdrm" "share/vulkan" "share/X11/XErrorDB" "share/X11/locale" "lib/i386-linux-gnu/vdpau/"

rm -rf "${graphics}"
mv "${new_shared_graphics}" "${graphics}"
